version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build: ./api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    container_name: backend
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    container_name: mysql
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    container_name: adminer