---
- hosts: all
  become: true
  become_user: root
  remote_user: vagrant
  gather_facts: false
  tasks:
    #- name: Wait for ssh to be up
    #  become: false
    #  wait_for:
    #    port: 22
    #    delay: 5
    #    connect_timeout: 5
    #    timeout: 360
    #    host: "{{ ansible_host }}"
    #  delegate_to: localhost

    - name: Installs python
      raw: apt-get update && apt-get install -y python

    - name: Kill previous instance of HTTP server
      shell: kill $(ps aux | grep '[p]ython3 http.server' | awk '{print $2}')

    - name: Run python HTTP server
      shell: nohup python3 -m http.server 8000 </dev/null >/dev/null 2>&1 &
      tags: run

    - name: Final greeting
      pause:
        seconds: 1
        echo: false
        prompt: "Don't worry about all the red above; if you made it here, your Vagrant VMs are probably fine !"